import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Test Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div><button><a href="/test_drf"><h1>TestDRFapi</h1></a></button></div>
      <div><button><a href="/testpage"><h1>TestPage</h1></a></button></div>
      <div><button><a href="http://localhost:3000"><h1>HOME</h1></a></button></div>
      {children}
      </body>
    </html>
  );
}
